version: '3'
 
services:
    apache_1:
        container_name: apache_1
        build: ./apache_1
        ports: 
          - 8085:80
    apache_2:
        container_name: apache_2
        build: ./apache_2
        ports:
          - 8086:80
    haproxy_img:
        container_name: haproxy
        build: ./haproxy
        ports:
          - 80:80